eCommerce/Controllers/DashboardController.cs
using eCommerce.Data;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace eCommerce.Controllers
{
    //heredar del controlador base
    [Authorize(Policy = "RequireAdminOrStaff")]
    public class DashboardController : BaseController
    {
        
        public DashboardController(AppDbContext context):base(context) 
        {
            
        }

        //Vista para mostrar los enlaces a otros cruds
        public IActionResult Index()
        {
            return View();
        }
    }
}

eCommerce/Controllers/PerfilController.cs
using eCommerce.Data;
using eCommerce.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace eCommerce.Controllers
{
    public class PerfilController : BaseController
    {

        public PerfilController(AppDbContext context) : base(context)
        {

        }

        //obtener informacion del usuario
        public async Task<IActionResult> Details(int? id)
        {
            //si el id es nulo
           if (id == null)
           {
                //retornar no encontrado
                return NotFound();
           }

            var usuario = await _context.Usuarios
                 //incluir direcciones del usuario para permitirle manejarlas
                 .Include(u => u.Direcciones)
                 .FirstOrDefaultAsync(u => u.UsuarioId == id);

            //validar
            if (usuario == null)
            {
                return NotFound();
            }

            return View(usuario);

        }

        //agregar direccion -GET
        public IActionResult AgregarDireccion( int id)
        {
            //enviar id del usuario en un viewbag
            ViewBag.Id = id;
            return View();
        }

        //POST
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> AgregarDireccion( Direccion direccion, int id)
        {
            //control de errores
            try
            {
                var usuario = await _context.Usuarios.FirstOrDefaultAsync(u => u.UsuarioId == id);
                if (usuario != null)
                {
                    //asignar valor a la propiedad direcciona
                    direccion.Usuario = usuario;
                }
                //agregar y guardar
                _context.Add(direccion);
                await _context.SaveChangesAsync();

                return RedirectToAction("Details", new { id });
            }
            catch (Exception e)
            {

               return View(direccion);
            }

            //buscar el usaurio
         
        }

    }
}

eCommerce/Views/Shared/Partials/_Header.cshtml
@using System.Security.Claims

<header>

    @*Barra de navegacion*@
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">

        <div class="container-fluid mx-5">
            <a class="navbar-brand" asp-controller="Home" asp-action="Index">Ferretería.NET</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
                    aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="navbar-collapse collapse d-sm-inline-flex justify-content-betwee" id="navbarSupportedContent">
                @*Ver los productos*@
                <form class="form-inline mx-auto" asp-controller="Home" asp-action="Productos" method="get">
                    <div class="input-group">
                        @*Barra de busqueda*@
                        <input class="form-control" type="search" placeholder="Buscar productos" aria-label="Buscaar" name="busqueda" />
                        <button class="btn btn-outline-secondary" type="submit">
                            <i class="fa-solid fa-magnifying-glass"></i>
                        </button>
                    </div>
                </form>

                @*Menu de opciones*@
                <ul class="navbar-nav">
                    <li class="nav-item">
                        @*Carrito*@
                        <a class="nav-link" asp-controller="Carrito" asp-action="Index">
                            <i class="fa-solid fa-cart-shopping"></i>
                            <span class="badge badge-pill badge-danger bg-primary">
                                @ViewBag.NumeroProductos
                            </span>
                        </a>
                    </li>

                    @*Perfil - validar usuario autenticado*@
                    @if (User.Identity != null && User.Identity.IsAuthenticated)
                    {
                        @*Asignar nombre del usuario*@
                        string nombreUsuario = User.Identity.Name ?? "Desconocido";
                        @*Asignar Id del usuario*@
                        string idUsuario = User.FindFirstValue(ClaimTypes.NameIdentifier);


                        @*Opciones solo para usuarios autenticados*@
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" data-bs-toggle="dropdown" aria-expanded="false">
                                <i class="fa-regular fa-user"> @nombreUsuario</i>
                            </a>
                            <ul class="dropdown-menu">
                                <li>
                                    <a class="dropdown-item" asp-controller="Perfil" asp-action="Details" asp-route-id="@idUsuario">Perfil</a>
                                </li>
                              

                                @*Opciones solo para usuarios administradores*@
                                @*validar*@
                                @if (User.FindFirstValue(ClaimTypes.Role) == "Administrador")
                                {
                                    <li>
                                        <a class="dropdown-item" asp-controller="Dashboard" asp-action="Index">Dashboard</a>
                                    </li>
                                }

                                <li>
                                    <a class="dropdown-item" asp-controller="Account" asp-action="Logout">Cerrar sesión</a>
                                </li>

                                <li><hr class="dropdown-divider"/></li>
        
                            </ul>
                        </li>
                    }
                    else
                    {
                        @*Opciones para usuarios no autenticados-login*@
                        <li class="nav-item">
                            <a class="nav-link" asp-controller="Account" asp-action="Login">
                                <i class="fa-regular fa-user"></i>
                            </a>
                        </li>
                    }

                </ul>

            </div>

        </div>

    </nav>
    @*Barra de navegacion-end*@

</header>

eCommerce/Views/Shared/Partials/_ProductosPartial.cshtml
@using eCommerce.Models.ViewModels;
@model ProductosPaginadosViewModel
@if(!string.IsNullOrEmpty(Model.NombreCategoriaSeleccionada))
{
    <div class="alert-info">
        Departamento seleccionado: @Model.NombreCategoriaSeleccionada
    </div>
}

<div class="row" id="productosContainer">
    @if (Model.Productos.Count==0)
    {
        <div class="col-md-12">
            <p>No se econtraron productos que coincidan con tu búsqueda.</p>
        </div>
    }
    else
    {
        @foreach (var producto in Model.Productos)
        {
            @*Crear tarjetas para los productos*@
            <div class="col-md-4 col-sm-6 mb-4 productoItem" data-categoria="@producto.CategoriaId">
                <div class="card h-100 d-grid">
                    <a href="@Url.Action("DetalleProducto","Home" , new{id = producto.ProductoId})">
                        <img class="card-img-top" src="@producto.Imagen" alt="Imagen del producto" />
                    </a>

                    <div class="card-body">
                        <h5 class="card-title text-center">
                            <a href="@Url.Action("DetalleProducto","Home" ,
                            new{id = producto.ProductoId})">@producto.Nombre</a>
                        </h5>
                        <p class="card-text">@producto.Descripcion</p>
                    </div>

                    <ul class="list-group list-group-flush text-center">
                        <li class="list-group-item">Modelo : @producto.Modelo</li>
                        <li class="list-group-item font-weight-bold">@string.Format("{0:C}", producto.Precio)</li>
                    </ul>

                    <div class="card-body mt-auto">
                        @*Validar el stock*@
                        @if (producto.Stock < 1)
                        {
                            <div class="alert alert-danger" role="alert">
                                <i class="fas fa-exclamation-circle"></i> Agotado
                            </div>
                        }
                        else
                        {
                            @*Agregar productos al carrito*@
                            <form method="post" action="@Url.Action("AgregarProducto")" class="d-flex">
                                @*Enviar los parametros dle metodo*@
                                <input type="hidden" name="id" value="@producto.ProductoId" />
                                <input type="number" class="form-control mr-2" name="cantidad" value="1" min="1" max="@producto.Stock" />
                                <input type="hidden" name="busqueda" value="@Model.Busqueda" />
                                <input type="hidden" name="pagina" value="@Model.PaginaActual" />
                                <input type="hidden" name="categoriaId" value="@Model.CategoriaIdSeleccionada" />


                                <button type="submit" class="btn btn-outline-primary rounded-pill"> <i class="fas fa-cart-plus"> </i></button>
                            </form>
                        }
                    </div>

                </div>
            </div>
        }
    }
</div>

<nav>
    <ul class="pagination justify-content-center">
        @if (Model.TotalPaginas>1)
        {
            @for (int pagina = 1; pagina <= Model.TotalPaginas; pagina++)
            {
                <li class="page-item @pagina == Model.PaginaActual ?"active" : "">
                    <a class="page-link" href="@Url.Action("Productos","Home", new{pagina = pagina, categoriaId = Model.CategoriaIdSeleccionada,
                    busqueda = Model.Busqueda})">@pagina</a>
                </li>
            }
        }
    </ul>
</nav>